server:
  port: 8088
  servlet:
    context-path: /hakatonDemo

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
    datasource:
      driver-class-name: org.postgresql.Driver
    application:
      name: hakatonDemo
  datasource:
    driver-class-name: org.postgresql.Driver
    username: chaos
    password: chaos
    url: jdbc:postgresql://127.0.0.1:5432/hackatondb
rabbit:
  host: 127.0.0.1
  port: 5672